@RaceTelemetry.QueryApi_HostAddress = http://localhost:5120

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/drivers
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/drivers/LEC/laps
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/replay/metadata
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/drivers/LEC/laps/1/telemetry?channels=speed_kmh,throttle_pct,brake_pct,rpm,gear&sampleEvery=2&maxSamples=5000
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/compare/laps?driverA=LEC&lapA=1&driverB=VER&lapB=1&channels=speed_kmh,throttle_pct,brake_pct&timeStepMs=100
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/replay/chunk?fromMs=60000&durationMs=30000&drivers=LEC,VER&sampleEvery=2
Accept: application/json

###

GET {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/replay/context?fromMs=60000&durationMs=300000
Accept: application/json

###

POST {{RaceTelemetry.QueryApi_HostAddress}}/api/sessions/2025-italian-grand-prix-r/telemetry-events/search
Accept: application/json
Content-Type: application/json

{
  "eventTypes": ["high_speed", "hard_braking"],
  "drivers": ["LEC"],
  "fromMs": 0,
  "durationMs": 300000,
  "limit": 100
}
