<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <ProjectReference Include="..\RaceTelemetry.Contracts\RaceTelemetry.Contracts.csproj" />
    <ProjectReference Include="..\RaceTelemetry.Data\RaceTelemetry.Data.csproj" />
    <ProjectReference Include="..\RaceTelemetry.ServiceDefaults\RaceTelemetry.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
